### ISSUE TITLE
Will threads use locks properly?

### ISSUE THREAD

**Issue by littlecube8152** [NTU-SP/SP2024_HW3_release#2]
Does our threading library need to handle automatic release of read/write lock when the thread exits (while still holding the lock), and lock conversions (when it already holds one type and wishes to have another)?
In other words, can we assume that threads are well-behaved?

I am querying this because I did not find restriction about locks, nor specification telling us to handle it.

Thank you for reviewing this issue.

**Comment by seantsao00** [comment]
Thank you for reviewing this issue. A correct thread routine, either from the spec or TAs' implementations, must:

- Release all held locks before exiting.
- Avoid acquiring locks it already holds or different locks while holding another.
- Not release locks it does not hold.

Please feel free to ask any further questions!
